### ISSUE TITLE
Не работает на RK-M170S-E

### ISSUE THREAD

**Issue by Nafania** [ClusterM/skykettle-ha#14]
В логах вот  такое

```Logger: custom_components.skykettle.kettle_connection
Source: custom_components/skykettle/kettle_connection.py:140
Integration: SkyKettle ([documentation](https://github.com/ClusterM/skykettle-ha/blob/master/README.md), [issues](https://github.com/ClusterM/skykettle-ha/issues))
First occurred: 10:36:17 PM (1 occurrences)
Last logged: 10:36:17 PM
Can't terminate, error (AttributeError): 'NoneType' object has no attribute 'isalive'```

```Logger: custom_components.skykettle.kettle_connection
Source: custom_components/skykettle/kettle_connection.py:278
Integration: SkyKettle ([documentation](https://github.com/ClusterM/skykettle-ha/blob/master/README.md), [issues](https://github.com/ClusterM/skykettle-ha/issues))
First occurred: 10:36:28 PM (2 occurrences)
Last logged: 10:48:52 PM
Can't set mode to (4, 85) for 30 seconds, stop trying```

```Logger: custom_components.skykettle.kettle_connection
Source: custom_components/skykettle/kettle_connection.py:291
Integration: SkyKettle ([documentation](https://github.com/ClusterM/skykettle-ha/blob/master/README.md), [issues](https://github.com/ClusterM/skykettle-ha/issues))
First occurred: 10:33:51 PM (41 occurrences)
Last logged: 10:51:39 PM

    Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 112, in get_status r = await self.command(SkyKettle.COMMAND_GET_STATUS) File "/config/custom_components/skykettle/kettle_connection.py", line 81, in command raise IOError("Disconnected") OSError: Disconnected During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 112, in get_status r = await self.command(SkyKettle.COMMAND_GET_STATUS) File "/config/custom_components/skykettle/kettle_connection.py", line 81, in command raise IOError("Disconnected") OSError: Disconnected During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 112, in get_status r = await self.command(SkyKettle.COMMAND_GET_STATUS) File "/config/custom_components/skykettle/kettle_connection.py", line 81, in command raise IOError("Disconnected") OSError: Disconnected During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes
    Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 178, in update await self._connect_if_need() File "/config/custom_components/skykettle/kettle_connection.py", line 158, in _connect_if_need raise ex File "/config/custom_components/skykettle/kettle_connection.py", line 154, in _connect_if_need await self._connect() File "/config/custom_components/skykettle/kettle_connection.py", line 105, in _connect await self._child.expect(r"Connection successful.*?\[LE\]> ", async_=True) File "/usr/local/lib/python3.9/site-packages/pexpect/_async.py", line 28, in expect_async return expecter.timeout(e) File "/usr/local/lib/python3.9/site-packages/pexpect/expect.py", line 144, in timeout raise exc pexpect.exceptions.TIMEOUT: <pexpect.pty_spawn.spawn object at 0x7f77fdc580> command: /usr/bin/gatttool args: ['/usr/bin/gatttool', '-I', '-t', 'random', '-b', 'D3:A5:D5:66:8C:75'] buffer (last 100 chars): b'91mError: \x1b[0mconnect to D3:A5:D5:66:8C:75: Function not implemented (38)\r\n[D3:A5:D5:66:8C:75][LE]> ' before (last 100 chars): b'91mError: \x1b[0mconnect to D3:A5:D5:66:8C:75: Function not implemented (38)\r\n[D3:A5:D5:66:8C:75][LE]> ' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 443 child_fd: 68 closed: False timeout: 1.5 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile(b'Connection successful.*?\\[LE\\]> ') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes
    Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes
    Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 178, in update await self._connect_if_need() File "/config/custom_components/skykettle/kettle_connection.py", line 158, in _connect_if_need raise ex File "/config/custom_components/skykettle/kettle_connection.py", line 154, in _connect_if_need await self._connect() File "/config/custom_components/skykettle/kettle_connection.py", line 105, in _connect await self._child.expect(r"Connection successful.*?\[LE\]> ", async_=True) File "/usr/local/lib/python3.9/site-packages/pexpect/_async.py", line 28, in expect_async return expecter.timeout(e) File "/usr/local/lib/python3.9/site-packages/pexpect/expect.py", line 144, in timeout raise exc pexpect.exceptions.TIMEOUT: <pexpect.pty_spawn.spawn object at 0x7f785af610> command: /usr/bin/gatttool args: ['/usr/bin/gatttool', '-I', '-t', 'random', '-b', 'D3:A5:D5:66:8C:75'] buffer (last 100 chars): b'91mError: \x1b[0mconnect to D3:A5:D5:66:8C:75: Function not implemented (38)\r\n[D3:A5:D5:66:8C:75][LE]> ' before (last 100 chars): b'91mError: \x1b[0mconnect to D3:A5:D5:66:8C:75: Function not implemented (38)\r\n[D3:A5:D5:66:8C:75][LE]> ' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 457 child_fd: 30 closed: False timeout: 1.5 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile(b'Connection successful.*?\\[LE\\]> ') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes
    Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 178, in update await self._connect_if_need() File "/config/custom_components/skykettle/kettle_connection.py", line 158, in _connect_if_need raise ex File "/config/custom_components/skykettle/kettle_connection.py", line 154, in _connect_if_need await self._connect() File "/config/custom_components/skykettle/kettle_connection.py", line 105, in _connect await self._child.expect(r"Connection successful.*?\[LE\]> ", async_=True) File "/usr/local/lib/python3.9/site-packages/pexpect/_async.py", line 28, in expect_async return expecter.timeout(e) File "/usr/local/lib/python3.9/site-packages/pexpect/expect.py", line 144, in timeout raise exc pexpect.exceptions.TIMEOUT: <pexpect.pty_spawn.spawn object at 0x7f78fa4a90> command: /usr/bin/gatttool args: ['/usr/bin/gatttool', '-I', '-t', 'random', '-b', 'D3:A5:D5:66:8C:75'] buffer (last 100 chars): b'91mError: \x1b[0mconnect to D3:A5:D5:66:8C:75: Function not implemented (38)\r\n[D3:A5:D5:66:8C:75][LE]> ' before (last 100 chars): b'91mError: \x1b[0mconnect to D3:A5:D5:66:8C:75: Function not implemented (38)\r\n[D3:A5:D5:66:8C:75][LE]> ' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 461 child_fd: 40 closed: False timeout: 1.5 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile(b'Connection successful.*?\\[LE\\]> ') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/skykettle/kettle_connection.py", line 183, in update self._status = await self.get_status() File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r)) struct.error: unpack requires a buffer of 16 bytes```

**Comment by ClusterM** [comment]
Тут скорее необычный ответ чайника. Какая модель чайника, какая прошивка? Можете включить debug лог:

**Comment by Nafania** [comment]
@ClusterM модель чайника RK-M170S-E, версия прошивка 4.12 согласно оф приложению

Дебаг

```2022-04-02 18:39:30 DEBUG (MainThread) [custom_components.skykettle.config_flow] Filtered scan result: [BleDevice(mac='D3:A5:D5:66:8C:75', name='RK-M170S')]
2022-04-02 18:40:17 INFO (SyncWorker_4) [custom_components.xiaomi_miot.core.miio2miot] Got miio props for miot: ['192.168.1.90', {'power': 'on', 'mode': 'high', 'humidity': 39, 'temperature': 23.4, 'buzzer': 'off', 'child_lock': 'off', 'depth': 118}]
2022-04-02 18:40:26 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-02 18:40:26 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-02 18:40:28 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-02 18:40:28 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [fd ca 15 e4 52 30 a2 9d]
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [6d 6e 48 62 30 2a 00 00]
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1648914029 (2022-04-02 18:40:29), offset=10800 (GMT+3.00)
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 04 0c
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 4.12
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 1c 00 00 0c 00 01 00
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Disconnected
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
2022-04-02 18:40:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] error: unpack requires a buffer of 16 bytes, retry #1
2022-04-02 18:40:30 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-02 18:40:30 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [fd ca 15 e4 52 30 a2 9d]
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [70 6e 48 62 30 2a 00 00]
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1648914032 (2022-04-02 18:40:32), offset=10800 (GMT+3.00)
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 04 0c
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 4.12
2022-04-02 18:40:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
2022-04-02 18:40:33 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 1c 00 00 0c 00 01 00
2022-04-02 18:40:33 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Disconnected
2022-04-02 18:40:33 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
2022-04-02 18:40:33 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] error: unpack requires a buffer of 16 bytes, retry #2
2022-04-02 18:40:33 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-02 18:40:33 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-02 18:40:35 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-02 18:40:35 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [fd ca 15 e4 52 30 a2 9d]
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [74 6e 48 62 30 2a 00 00]
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1648914036 (2022-04-02 18:40:36), offset=10800 (GMT+3.00)
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 04 0c
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 4.12
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 1c 00 00 0c 00 01 00
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Disconnected
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
2022-04-02 18:40:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] error: unpack requires a buffer of 16 bytes, retry #3
2022-04-02 18:40:37 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-02 18:40:37 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [fd ca 15 e4 52 30 a2 9d]
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [77 6e 48 62 30 2a 00 00]
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1648914039 (2022-04-02 18:40:39), offset=10800 (GMT+3.00)
2022-04-02 18:40:39 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 04 0c
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 4.12
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 1c 00 00 0c 00 01 00
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Disconnected
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] error: unpack requires a buffer of 16 bytes, retry #4
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-02 18:40:40 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-02 18:40:42 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-02 18:40:42 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [fd ca 15 e4 52 30 a2 9d]
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [7b 6e 48 62 30 2a 00 00]
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1648914043 (2022-04-02 18:40:43), offset=10800 (GMT+3.00)
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 04 0c
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 4.12
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 1c 00 00 0c 00 01 00
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Disconnected
2022-04-02 18:40:43 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
2022-04-02 18:40:43 ERROR (MainThread) [custom_components.skykettle.kettle_connection] Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 184, in update
self._status = await self.get_status()
File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status
status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r))
struct.error: unpack requires a buffer of 16 bytes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 184, in update
self._status = await self.get_status()
File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status
status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r))
struct.error: unpack requires a buffer of 16 bytes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 184, in update
self._status = await self.get_status()
File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status
status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r))
struct.error: unpack requires a buffer of 16 bytes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 184, in update
self._status = await self.get_status()
File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status
status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r))
struct.error: unpack requires a buffer of 16 bytes
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 184, in update
self._status = await self.get_status()
File "/config/custom_components/skykettle/skykettle.py", line 113, in get_status
status = SkyKettle.Status(*unpack("<BxBx?BHBxxxxBxx", r))
struct.error: unpack requires a buffer of 16 bytes
2022-04-02 18:40:43 INFO (MainThread) [custom_components.skykettle.kettle_connection] Disposed.```

**Comment by ClusterM** [comment]
А до обновления HA всё работало? Прошивка не обновлялась перед тем, как всё сломалось?

**Comment by Nafania** [comment]
А до этого я не пробовал) У меня в принципе её работает. Прошивка чайника не обновлялась

**Comment by ClusterM** [comment]
Надо тогда разбираться, какие байты за что отвечают.

**Comment by Nafania** [comment]
Как я могу в этом помочь?

**Comment by ClusterM** [comment]
Можете попробовать версию из master?

**Comment by Nafania** [comment]
У меня с тех пор чайник сломался и я купил новый, который полностью
совместим)

вс, 17 июл. 2022 г., 13:40 ClusterM ***@***.***>:

**Comment by ClusterM** [comment]
Если вы запишете более подробный лог bluetooth трафика, где по очереди включаете режимы (подогрев, кипячение, кипячение+подогрев, выключение), то сообщество будет вам очень благодавно! Не один я пытаюсь изучить эту модель.

Как это сделать описано тут: https://github.com/ClusterM/skykettle-ha/wiki/How-to-get-HCI-log-on-Android-device
