### ISSUE TITLE
Connection issue after upgrade to 1.4

### ISSUE THREAD

**Issue by rchovan** [ClusterM/skykettle-ha#15]
Hi, 
after upgrade I have connection issue. Can't connect to my kettle. Tried to remove integration and installed again. Now I can't pair my kettle. 

Tried with AUTO or selected BT device, without success. 

![image](https://user-images.githubusercontent.com/6713920/163706068-94c0ef47-5be9-4c14-a573-3112b1567106.png)

`
2022-04-17 09:56:12 INFO (SyncWorker_0) [homeassistant.loader] Loaded skykettle from custom_components.skykettle
2022-04-17 09:56:12 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skykettle which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-17 09:56:12 INFO (MainThread) [custom_components.hacs] <Integration ClusterM/skykettle-ha> Post installation steps completed
2022-04-17 09:58:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-17 09:58:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-17 09:58:29 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-17 09:58:30 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-17 09:58:31 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
2022-04-17 09:58:31 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Timeout, retry #1
2022-04-17 09:58:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-17 09:58:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-17 09:58:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-17 09:58:32 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-17 09:58:34 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
2022-04-17 09:58:34 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Timeout, retry #2
2022-04-17 09:58:34 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
2022-04-17 09:58:34 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Starting "gatttool"...
2022-04-17 09:58:34 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] "gatttool" started
2022-04-17 09:58:35 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
2022-04-17 09:58:36 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
`

![image](https://user-images.githubusercontent.com/6713920/163706073-51c3b661-091d-48c8-8af8-7ae49cc5145b.png)

**Comment by ClusterM** [comment]
Sorry for not so fast answer. I'll check it.

**Comment by ClusterM** [comment]
Can you share DEBUG level log?

**Comment by rchovan** [comment]
I have already shared.  If you need something more,  please tell me what to do.

**Comment by ClusterM** [comment]
> I have already shared.  If you need something more,  please tell me what to do.  

Oh, sorry. I'm stupid today :) Weird. Are you try to return to the previous version? I need to know if it will work again.

**Comment by rchovan** [comment]
Hi, 
tried versions 1.3 and even 1.2. I can't connect to this kettle anymore. And for sure, I've disabled BT on my phone where is official app installed. 

```
1098:2022-06-08 22:03:00 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
1099:2022-06-08 22:03:00 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Timeout, retry #1
1100:2022-06-08 22:03:01 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
1101:2022-06-08 22:03:01 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Staring gatttool...
1102:2022-06-08 22:03:01 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Started gatttool
1103:2022-06-08 22:03:01 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
1104:2022-06-08 22:03:03 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
1105:2022-06-08 22:03:03 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Timeout, retry #2
1106:2022-06-08 22:03:03 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
1107:2022-06-08 22:03:03 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Staring gatttool...
1108:2022-06-08 22:03:04 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Started gatttool
1109:2022-06-08 22:03:04 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
1110:2022-06-08 22:03:05 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Terminated
1111:2022-06-08 22:03:05 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Timeout, retry #3
1112:2022-06-08 22:03:06 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
1113:2022-06-08 22:03:06 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Staring gatttool...
1114:2022-06-08 22:03:06 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Started gatttool
1115:2022-06-08 22:03:06 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Attempting to connect...
```

**Comment by ClusterM** [comment]
Please install Home Assistant 2022.8.1 or newer and try version from master. It depends on the new "Bluetooth" integration now, so make sure that it's enabled and works.

**Comment by rchovan** [comment]
Hello, 
updated to Master (v2.0) but I can't add Integration:

![image](https://user-images.githubusercontent.com/6713920/184627467-9fa54a78-c920-4b79-a36e-f125d6e67239.png)


```
grep -i kettle home-assistant.log
2022-08-15 13:27:09.823 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skykettle which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-15 13:27:49.221 ERROR (MainThread) [custom_components.skykettle.config_flow] Traceback (most recent call last):
  File "/config/custom_components/skykettle/config_flow.py", line 74, in async_step_scan
2022-08-15 13:28:01.248 ERROR (MainThread) [custom_components.skykettle.config_flow] Traceback (most recent call last):
  File "/config/custom_components/skykettle/config_flow.py", line 74, in async_step_scan```

**Comment by ClusterM** [comment]
> Hello, updated to Master (v2.0) but I can't add Integration:

Make sure that new Bluetooth integration is installed and working.

**Comment by ClusterM** [comment]
> Adding my device

I need to add support for this model. I think that it's the same as RK-G200S. I added it to the current master. Try it.

**Comment by rchovan** [comment]
Tried several times, removed integration, restarted HA, added integration, restarted HA, adding device, it always fail with 
![image](https://user-images.githubusercontent.com/6713920/184680823-4ac52a6b-d011-41a4-9777-99873ec121be.png)

right after selecting integration from menu on device screen, before device selection


log:
```
2022-08-15 18:58:22.110 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skykettle which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-15 18:58:30.778 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.hacs, old_state=<state sensor.hacs=unknown; unit_of_measurement=pending update(s), icon=hacs:hacs, friendly_name=hacs @ 2022-08-15T18:58:26.519385+02:00>, new_state=<state sensor.hacs=1; repositories=[{'name': 'ClusterM/skykettle-ha', 'display_name': 'SkyKettle', 'installed_version': '62c776d', 'available_version': 'v2.0'}], unit_of_measurement=pending update(s), icon=hacs:hacs, friendly_name=hacs @ 2022-08-15T18:58:30.778221+02:00>>
2022-08-15 18:58:31.163 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.hacs, old_state=<state sensor.hacs=1; repositories=[{'name': 'ClusterM/skykettle-ha', 'display_name': 'SkyKettle', 'installed_version': '62c776d', 'available_version': 'v2.0'}], unit_of_measurement=pending update(s), icon=hacs:hacs, friendly_name=hacs @ 2022-08-15T18:58:30.778221+02:00>, new_state=<state sensor.hacs=0; repositories=[], unit_of_measurement=pending update(s), icon=hacs:hacs, friendly_name=hacs @ 2022-08-15T18:58:31.163187+02:00>>
```

**Comment by ClusterM** [comment]
This log is not from skykettle integration.

**Comment by ClusterM** [comment]
https://github.com/ClusterM/skykettle-ha/wiki/How-to-get-Home-Assistant-log

**Comment by rchovan** [comment]
sorry, can't get it workng. Uninstalled integration over HACS, restarted HA, installed integration, restarted HA, still can't add device, and no record in home-assistant.log file. 

configuration.yaml
```
logger:
  default: info
  logs:
    #zha zigbee info
    homeassistant.components.zha: debug
    zigpy: debug
    zigpy_deconz: debug
    zigpy_zigate: debug
    homeassistant.core: debug
    zhaquirks: debug
    hacs: info
    limitlessled: info
    asyncio: info
    bellows: info
    custom_components.zha_map: info
    custom_components.ble_monitor: info
    homeassistant.components.heos: info
    pyheos: info
    homeassistant.components.telegram_bot: info
    homeassistant.components.rest: info
    homeassistant.components.rest.sensor: info
    homeassistant.components.xiaomi_aqara: debug
    homeassistant.components.stream: debug
    homeassistant.components.stream.stream.camera.cam_down: debug
    custom_components.skykettle: debug
```

grep -i kettle home-assistant.log
```
2022-08-17 11:56:42.622 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skykettle which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

devices > add integration > 
```
SkyKettle
Can't find any supported kettle. Please make sure that your kettle is in the list of supported devices and it's on the stand.
```

**Comment by rchovan** [comment]
it started working after update HA to 2022.09 but communication isn't reliable.

![image](https://user-images.githubusercontent.com/6713920/189822780-9796fb98-d0d9-45e6-a4ef-99e5c57c5c37.png)

I'll buy new BT USB dongle, one from HA supported, and I'll write more info after testing.

**Comment by rchovan** [comment]
Hi, 
I've bought Asus BT-500 USB which is in supported by HA. When I enable SkyKettle integration, it works for some time, but then it breaks, and it block another BT devices. 

This is Xiaomi BT humidity/temperature sensor with LCD. 
red - skykettle enabled
green - skykettle disabled

![image](https://user-images.githubusercontent.com/6713920/190590286-ed19c79b-09d9-4745-b69b-23968c96bec4.png)

**Comment by ClusterM** [comment]
> and it block another BT devices

> No other BT integrations.,

So are you using other BT integrations or not?

**Comment by rchovan** [comment]
Integration is still only one. Bluetooth from HA, which Skykettle uses too. Devices are 3. 2x xiaomi temperature and 1x kettle.

**Comment by ClusterM** [comment]
I don't know how to fix it because i can't reproduce problem :(

**Comment by rchovan** [comment]
Hi, I have debug log from yesterday 

last successful connection
```
home-assistant.log.1:2022-10-11 20:34:18.185 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connecting to the Kettle...
home-assistant.log.1:2022-10-11 20:34:18.186 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connected to the Kettle
home-assistant.log.1:2022-10-11 20:34:18.187 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Subscribed to RX
home-assistant.log.1:2022-10-11 20:34:18.187 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command ff, data: [d3 de 3c 1a 88 c1 30 f2]
home-assistant.log.1:2022-10-11 20:34:18.370 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 02
home-assistant.log.1:2022-10-11 20:34:18.370 DEBUG (MainThread) [custom_components.skykettle.skykettle] Auth: ok=True
home-assistant.log.1:2022-10-11 20:34:18.370 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Auth ok
home-assistant.log.1:2022-10-11 20:34:18.370 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 01, data: []
home-assistant.log.1:2022-10-11 20:34:18.473 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 04 0b
home-assistant.log.1:2022-10-11 20:34:18.473 DEBUG (MainThread) [custom_components.skykettle.skykettle] Version: 4.11
home-assistant.log.1:2022-10-11 20:34:18.473 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 6e, data: [2a b7 45 63 20 1c 00 00]
home-assistant.log.1:2022-10-11 20:34:18.680 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00
home-assistant.log.1:2022-10-11 20:34:18.680 DEBUG (MainThread) [custom_components.skykettle.skykettle] Writed time=1665513258 (2022-10-11 20:34:18), offset=7200 (GMT+2.00)
home-assistant.log.1:2022-10-11 20:34:18.680 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 06, data: []
home-assistant.log.1:2022-10-11 20:34:18.835 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 00 00 01 1a 0f 00 00 00 00 00 00 80 00 00
home-assistant.log.1:2022-10-11 20:34:18.836 DEBUG (MainThread) [custom_components.skykettle.skykettle] Status: mode=0 (Boil), is_on=False, target_temp=0, current_temp=26, sound_enabled=True, color_interval=15, boil_time=0
home-assistant.log.1:2022-10-11 20:34:18.836 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 47, data: [00]
home-assistant.log.1:2022-10-11 20:34:19.017 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 3d cc 05 00 08 8b 03 00 d2 0e 00 00 00 00
home-assistant.log.1:2022-10-11 20:34:19.017 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 50, data: [00]
home-assistant.log.1:2022-10-11 20:34:19.197 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 00 36 09 00 00 00 00 00 00 00 00 00 00 00
home-assistant.log.1:2022-10-11 20:34:19.198 DEBUG (MainThread) [custom_components.skykettle.skykettle] Stats: ontime=4 days, 9:32:45, energy_wh=232200, user_on_count=2358, heater_on_count=3794
home-assistant.log.1:2022-10-11 20:34:19.198 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 35, data: [00]
home-assistant.log.1:2022-10-11 20:34:19.384 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 01 00 00
home-assistant.log.1:2022-10-11 20:34:19.384 DEBUG (MainThread) [custom_components.skykettle.skykettle] Light with type=0 (boiling_light) is on
home-assistant.log.1:2022-10-11 20:34:19.384 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 35, data: [c8]
home-assistant.log.1:2022-10-11 20:34:19.542 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: c8 00 01 c8 00
home-assistant.log.1:2022-10-11 20:34:19.542 DEBUG (MainThread) [custom_components.skykettle.skykettle] Light with type=200 (sync_light) is on
home-assistant.log.1:2022-10-11 20:34:19.542 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 30, data: []
home-assistant.log.1:2022-10-11 20:34:19.645 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 08 00
home-assistant.log.1:2022-10-11 20:34:19.645 DEBUG (MainThread) [custom_components.skykettle.skykettle] Lamp auto off hours=8
home-assistant.log.1:2022-10-11 20:34:19.645 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 52, data: [00]
home-assistant.log.1:2022-10-11 20:34:19.791 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 00 30 00 02 00 00 00 00 00 00 00 00 00 00 00
home-assistant.log.1:2022-10-11 20:34:19.791 DEBUG (MainThread) [custom_components.skykettle.skykettle] Fresh water notification is off, unknown1=48, water_freshness_hours=2
home-assistant.log.1:2022-10-11 20:34:19.791 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 33, data: [00]
home-assistant.log.1:2022-10-11 20:34:19.939 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 00 23 ff 00 00 ff 46 ff 00 ff 00 64 ff ff 00 00
home-assistant.log.1:2022-10-11 20:34:19.939 DEBUG (MainThread) [custom_components.skykettle.skykettle] ColorsSet(light_type=0, temp_low=35, brightness=255, r_low=0, g_low=0, b_low=255, temp_mid=70, unknown1=255, r_mid=0, g_mid=255, b_mid=0, temp_high=100, unknown2=255, r_high=255, g_high=0, b_high=0)
home-assistant.log.1:2022-10-11 20:34:19.939 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Writing command 33, data: [01]
home-assistant.log.1:2022-10-11 20:34:20.172 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Received: 01 00 7f 00 00 ff 32 7f 00 ff 00 64 7f ff 00 00
home-assistant.log.1:2022-10-11 20:34:20.172 DEBUG (MainThread) [custom_components.skykettle.skykettle] ColorsSet(light_type=1, temp_low=0, brightness=127, r_low=0, g_low=0, b_low=255, temp_mid=50, unknown1=127, r_mid=0, g_mid=255, b_mid=0, temp_high=100, unknown2=127, r_high=255, g_high=0, b_high=0)
home-assistant.log.1:2022-10-11 20:34:20.172 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Disconnected
home-assistant.log.1:2022-10-11 20:34:50.175 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
home-assistant.log.1:2022-10-11 20:34:50.175 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connecting to the Kettle...
home-assistant.log.1:2022-10-11 20:35:00.176 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] TimeoutError: , retry #1
home-assistant.log.1:2022-10-11 20:35:00.677 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
home-assistant.log.1:2022-10-11 20:35:00.677 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connecting to the Kettle...
home-assistant.log.1:2022-10-11 20:35:00.679 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist
home-assistant.log.1:2022-10-11 20:35:01.180 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
```

next connection does not work
```
home-assistant.log.1:2022-10-11 20:35:01.181 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connecting to the Kettle...
home-assistant.log.1:2022-10-11 20:35:01.189 WARNING (MainThread) [custom_components.skykettle.kettle_connection] Can't update status, BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist
home-assistant.log.1:2022-10-11 20:35:01.192 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Traceback (most recent call last):
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 153, in update
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 133, in _connect_if_need
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 128, in _connect_if_need
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 94, in _connect
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 153, in update
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 133, in _connect_if_need
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 128, in _connect_if_need
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 94, in _connect
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 153, in update
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 133, in _connect_if_need
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 128, in _connect_if_need
home-assistant.log.1:  File "/config/custom_components/skykettle/kettle_connection.py", line 94, in _connect
home-assistant.log.1:2022-10-11 20:35:31.212 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Updating
home-assistant.log.1:2022-10-11 20:35:31.212 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Connecting to the Kettle...
```

and after that, is BT dongle not usable, 
dmesg output
```
[Ut okt 11 20:35:33 2022] Bluetooth: hci0: Opcode 0x2043 failed: -110
[Ut okt 11 20:35:33 2022] Bluetooth: hci0: request failed to create LE connection: err -110
[Ut okt 11 20:35:33 2022] general protection fault, probably for non-canonical address 0xdab8fcb526e9b029: 0000 [#1] PREEMPT SMP PTI
[Ut okt 11 20:35:33 2022] CPU: 2 PID: 240014 Comm: kworker/u17:2 Not tainted 5.17.0-1-amd64 #1  Debian 5.17.3-1
[Ut okt 11 20:35:33 2022] Hardware name: ASUS All Series/H87I-PLUS, BIOS 2003 11/05/2014
[Ut okt 11 20:35:33 2022] Workqueue: hci0 hci_cmd_sync_work [bluetooth]
[Ut okt 11 20:35:33 2022] RIP: 0010:hci_pend_le_action_lookup+0x5/0x40 [bluetooth]
[Ut okt 11 20:35:33 2022] Code: 8b 00 48 39 f8 74 1b 44 8b 06 44 39 40 20 75 ef 44 0f b7 4e 04 66 44 39 48 24 75 e3 38 50 26 75 de c3 31 c0 c3 0f 1f 44 00 00 <48> 8b 0f 48 8d 41 f0 48 39 cf 75 0f eb 28 48 8b 48 10 48 8d 41 f0
[Ut okt 11 20:35:33 2022] RSP: 0018:ffffb4fc81973dd0 EFLAGS: 00010296
[Ut okt 11 20:35:33 2022] RAX: 0000000000000000 RBX: 00000000ffffff92 RCX: 0000000000000000
[Ut okt 11 20:35:33 2022] RDX: 0000000000000038 RSI: ffff9cb2bf73d014 RDI: dab8fcb526e9b029
[Ut okt 11 20:35:33 2022] RBP: ffff9cb2bf73d000 R08: 0000000000000000 R09: ffffb4fc81973bf0
[Ut okt 11 20:35:33 2022] R10: ffffb4fc81973be8 R11: ffffffff98ed1568 R12: 0000000000000092
[Ut okt 11 20:35:33 2022] R13: dab8fcb526e9a381 R14: ffff9cb2bf73d014 R15: 0000000000000092
[Ut okt 11 20:35:33 2022] FS:  0000000000000000(0000) GS:ffff9cb54fa80000(0000) knlGS:0000000000000000
[Ut okt 11 20:35:33 2022] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[Ut okt 11 20:35:33 2022] CR2: 000000c0008b3000 CR3: 000000014b914005 CR4: 00000000001706e0
[Ut okt 11 20:35:33 2022] Call Trace:
[Ut okt 11 20:35:33 2022]  <TASK>
[Ut okt 11 20:35:33 2022]  hci_le_conn_failed+0x3f/0x200 [bluetooth]
[Ut okt 11 20:35:33 2022]  create_le_conn_complete+0x53/0x80 [bluetooth]
[Ut okt 11 20:35:33 2022]  hci_cmd_sync_work+0xd2/0x160 [bluetooth]
[Ut okt 11 20:35:33 2022]  process_one_work+0x1e5/0x3b0
[Ut okt 11 20:35:33 2022]  worker_thread+0x50/0x3a0
[Ut okt 11 20:35:33 2022]  ? rescuer_thread+0x390/0x390
[Ut okt 11 20:35:33 2022]  kthread+0xe8/0x110
[Ut okt 11 20:35:33 2022]  ? kthread_complete_and_exit+0x20/0x20
[Ut okt 11 20:35:33 2022]  ret_from_fork+0x22/0x30
[Ut okt 11 20:35:33 2022]  </TASK>
```

**Comment by rchovan** [comment]
I have read at kernel.org, that this is kernel issue with BT driver. So I've upgraded my kernel 5.17 to 6.01. I still see same error in dmesg, but now integration is working and can communicate with all of 3 devices. 

Anyway, I'm experiencing this issue, where connection success rate drop during time from 100% to 0% and then back to 100%.

![image](https://user-images.githubusercontent.com/6713920/197516511-e46ba3fa-4595-4dce-b9c2-180d2230d47f.png)

Any hint ?
