### ISSUE TITLE
Нестабильное соединение с чайником

### ISSUE THREAD

**Issue by siriuske** [ClusterM/skykettle-ha#16]
Очень часто теряется коннект, в логах следуюющее
`Logger: homeassistant.util.async_
Source: util/async_.py:150
First occurred: 31 мая 2022 г., 20:28:30 (1674 occurrences)
Last logged: 15:17:05

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue for http doing blocking calls at homeassistant/components/http/request_context.py, line 27: context.set(request)
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 115: if self._child and self._child.isalive():
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/__init__.py, line 49: hass.data[DOMAIN][DATA_CANCEL] = ev.async_call_later(hass, td, poll)
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue for http doing blocking calls at homeassistant/components/http/security_filter.py, line 53: if FILTERS.search(request.query_string):
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue for mobile_app doing blocking calls at homeassistant/components/mobile_app/entity.py, line 123: self.async_write_ha_state()`

График выглядит очень рвано
![image](https://user-images.githubusercontent.com/61635979/171403441-8ea8ebc0-8b89-4fb3-9a76-98d7a48f1408.png)

**Comment by ClusterM** [comment]
Приветствую. Можно посмотреть лог уровня DEBUG?

**Comment by siriuske** [comment]
[home-assistant.log](https://github.com/ClusterM/skykettle-ha/files/8837564/home-assistant.log)
если все верно сделал, то вот они

**Comment by ClusterM** [comment]
Похоже на банально слабый сигнал. Чайник достаточно близко к блютус модулю находится? Есть возможность попробовать поставить его поближе и проверить?

**Comment by siriuske** [comment]
Попробую, странно что две недели до этого работал без перебоев

**Comment by siriuske** [comment]
Поставил чайник практически вплотную, не помогло

**Comment by ClusterM** [comment]
А какая сейчас версия используется?

**Comment by siriuske** [comment]
v1.4

**Comment by ClusterM** [comment]
> v1.4

Попробуйте откатиться к предыдущим версиям. Изменится ли что-нибудь?

**Comment by siriuske** [comment]
попробовал 1.3 и 1.2 в течении нескольких дней, результат такой же.
Т.е. картина следующая, сначала была установлена версия 1.4 и работала стабильно около пары недель и в один прекрасный момент стабильное соединение исчезло.

**Comment by ClusterM** [comment]
Очень странно. А никакие другие интеграции работающие с Bluetooth не используются? Они могут конфликтовать.

**Comment by siriuske** [comment]
хотел попробовать на внешнем свистке, но получил вот такую ошик
`Logger: custom_components.skykettle.config_flow
Source: custom_components/skykettle/config_flow.py:146
Integration: SkyKettle ([documentation](https://github.com/ClusterM/skykettle-ha/blob/master/README.md), [issues](https://github.com/ClusterM/skykettle-ha/issues))
First occurred: 01:20:21 (1 occurrences)
Last logged: 01:20:21

Traceback (most recent call last): File "/config/custom_components/skykettle/config_flow.py", line 125, in async_step_scan macs = await ble_scan(self.config.get(CONF_DEVICE, None), scan_time=BLE_SCAN_TIME) File "/config/custom_components/skykettle/ble_scan.py", line 38, in ble_scan raise Exception(err) Exception: Set scan parameters failed: I/O error`

Завести отдельный ишью?

**Comment by siriuske** [comment]
и кажется просто удаление интеграции и добавление заново устранило проблему, интересно сколько продержится

**Comment by Drafteed** [comment]
На блютус может очень сильно влиять [подключенный по USB 3.0 девайс](https://www.usb.org/sites/default/files/327216.pdf), например HDD. И кроме этого, обычный WiFi 2.4 тоже может перекрывать сигнал. Лично у меня при подключении HDD в порт USB 3.0 плата в 5 метрах от чайника его уже не берет.

**Comment by siriuske** [comment]
проблема точно не в качестве сигнала, после переустановки интеграции все работало стабильно около 5 дней, потом проблема с разрывами вернулась, отлично видно по графику
![image](https://user-images.githubusercontent.com/61635979/173765965-1bdc0b8f-1f5f-4830-8937-39a98819e6ca.png)

**Comment by siriuske** [comment]
`Logger: homeassistant.util.async_
Source: util/async_.py:157
First occurred: 11:28:55 (447 occurrences)
Last logged: 15:12:07

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for mikrotik_router doing blocking calls at custom_components/mikrotik_router/mikrotik_controller.py, line 576: await asyncio.wait_for(self.lock.acquire(), timeout=10)
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for skykettle doing blocking calls at custom_components/skykettle/kettle_connection.py, line 100: self._child = await self.hass.async_add_executor_job(pexpect.spawn, "gatttool", (['-i', self.adapter] if self.adapter else []) + ['-I', '-t', 'random', '-b', self._mac], KettleConnection.BLE_TIMEOUT)
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue for http doing blocking calls at homeassistant/components/http/view.py, line 56: msg = json.dumps(result, cls=JSONEncoder, allow_nan=False).encode("UTF-8")
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue for hassio doing blocking calls at homeassistant/components/hassio/handler.py, line 245: request = await self.websession.request(
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue for met doing blocking calls at homeassistant/components/met/__init__.py, line 182: resp = await self._weather_data.fetching_data()`

**Comment by ClusterM** [comment]
А какая модель чайника?

**Comment by siriuske** [comment]
Rk-g202s

**Comment by ClusterM** [comment]
Попробуйте версию из master. И запишите лог за продолжительное время, подождите хотя бы полчаса после загрузки HA.
И скажите, включено ли постоянное соединение с чайником в настройках интеграции?

**Comment by siriuske** [comment]
на мастер ветке при попытке подключения получаю ошибку
![image](https://user-images.githubusercontent.com/61635979/179394687-e9a35bb6-ed59-4ca6-a389-095eef16c1cd.png)
в логах
`Logger: aiohttp.server
Source: custom_components/skykettle/skykettle.py:85
Integration: SkyKettle ([documentation](https://github.com/ClusterM/skykettle-ha/blob/master/README.md), [issues](https://github.com/ClusterM/skykettle-ha/issues))
First occurred: 13:41:37 (4 occurrences)
Last logged: 13:43:24

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
[home-assistant.log](https://github.com/ClusterM/skykettle-ha/files/9127450/home-assistant.log)

  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/skykettle/config_flow.py", line 156, in async_step_connect
    kettle = KettleConnection(
  File "/config/custom_components/skykettle/kettle_connection.py", line 26, in __init__
    super().__init__(model)
  File "/config/custom_components/skykettle/skykettle.py", line 85, in __init__
    raise SkyKettleError("Unknown kettle model")
custom_components.skykettle.skykettle.SkyKettleError: Unknown kettle model`

ну и сами дебаг логи в аттаче

**Comment by ClusterM** [comment]
Виноват :( Попробуйте сейчас снова обновиться.

**Comment by siriuske** [comment]
[home-assistant (1).zip](https://github.com/ClusterM/skykettle-ha/files/9127755/home-assistant.1.zip)

**Comment by ClusterM** [comment]
Связь рвётся и не устанавливается абсолютно рандомно. Всё равно очень похоже на какие-то помехи или сонфликты с другим ПО. Я сейчас думаю перейти на другую библиотеку, посмотрим как будет с ней.

**Comment by Drafteed** [comment]
> Связь рвётся и не устанавливается абсолютно рандомно. Всё равно очень похоже на какие-то помехи или сонфликты с другим ПО. Я сейчас думаю перейти на другую библиотеку, посмотрим как будет с ней.

В новой версии HA [ввели поддержку Bluetooth](https://www.home-assistant.io/blog/2022/08/03/release-20228/) и вроде как на основе Bleak.

**Comment by AndyZ2121** [comment]
У меня рвется связь на 15-25с несколько раз в день, при этом уровень сигнала не опускается ниже 60% и раз в день рано утром падает в 0. Все бы ничего, но у меня настроено голосовое оповещение о включении и закипании чайника...) RK-G200S.

**Comment by ClusterM** [comment]
Пожалуйста, установите Home Assistant 2022.8.1 или новее и попробуйте версию из master. Она теперь работает через новую интеграцию "Bluetooth", так что убедитесь, что она включена и работает.

**Comment by siriuske** [comment]
Приветствую, на самом деле после установки версии 1.5 из релизной ветки, а не из мастера, все ок, не писал т.к. хотел потестить стабильность ведь ранее нестабильное соединение появлялось через несколько дней работы интеграции.
На 2.0 сейчас переползу но кажется что бага ушла в старом проявлении

**Comment by siriuske** [comment]
после перехода на 2.0 где-то сутки работало хорошо, но сейчас повисла интеграция хорошо видно по графику текущей температуры 
![image](https://user-images.githubusercontent.com/61635979/184960962-2008a0c0-2e9b-42dc-9d32-68529deda8e1.png)
при этом выглядит так как будто ХА думает что чайник живой но управление не работает
![image](https://user-images.githubusercontent.com/61635979/184961142-d6421322-58c9-4616-9f18-aa917ca27a12.png)
Есть дебаг лог с момента старта ХА, правда он весит около гига)

ЗЫ после рестарта ХА чайник недоступен

**Comment by siriuske** [comment]
UPD
в ночи чайник сам подтянулся, потеря связи в 9.40 утра это чайник не на подставке стоял
![image](https://user-images.githubusercontent.com/61635979/185072952-4e979fc7-b719-4f73-b3c9-9b76eb50b02d.png)

**Comment by siriuske** [comment]
и опять зависли показания, управление не работает

**Comment by AndyZ2121** [comment]
Я уж думал у меня чайник сломался... Появилась идея: а если попробовать сделать тестовую версию с ограниченным функционалом (более 20 сенсоров ведь не нужны постоянно, вдруг из-за этого) и оставить только кипячение, бойлер и подсветку/синхронизацию. Если идея зайдет, готов к тестам.

**Comment by siriuske** [comment]
врядли дело в этом, на версии 1.5 работало более 2х недель

**Comment by ClusterM** [comment]
> Есть дебаг лог с момента старта ХА, правда он весит около гига)

Не страшно :) Можно отфильтровать его по "skykettle".



> Я уж думал у меня чайник сломался... Появилась идея: а если попробовать сделать тестовую версию с ограниченным функционалом (более 20 сенсоров ведь не нужны постоянно, вдруг из-за этого) и оставить только кипячение, бойлер и подсветку/синхронизацию. Если идея зайдет, готов к тестам.

Дело точно не в этом.

**Comment by siriuske** [comment]
я немного соврал, чайник нашелся не сам, а был рестарт после обновления, т.е. первый рестарт не помог и чайник был не доступен, потом я обновил какой-то компонент и рестартанул ХА еще раз и чайник подхватился и проработал до утра.
Логи чуть позже фильтрану, сейчас нет в доступе ПК с чем-то лучше обычного ноутпада

**Comment by siriuske** [comment]
всетаки сам же и ожил 
![image](https://user-images.githubusercontent.com/61635979/185335158-69954eec-53da-4cc0-8a85-fc600b958284.png)
нужны логи оживания чайника?)

**Comment by Nemiroff** [comment]
В v1.20 часто теряется Коннект, если чайник был снят с подставки и был не доступен в момент отправки команды 06. Помогает перезагрузка HA или же перезагрузка самой конфигурации. Такое ощущение, что в главном цикле перехватывается исключение и цикл завершается, не смотря на то, что в настройках включено постоянное соединение

**Comment by Nemiroff** [comment]
Проверка состояния заканчивается таким варнингом
```2022-08-27 07:54:05.143 WARNING (MainThread) [custom_components.skykettle.kettle_connection] Can't update status, BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort
2022-08-27 07:54:05.152 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 148, in update
self._status = await self.get_status()
File "/config/custom_components/skykettle/skykettle.py", line 188, in get_status
r = await self.command(SkyKettle.COMMAND_GET_STATUS)
File "/config/custom_components/skykettle/kettle_connection.py", line 75, in command
if monotonic() >= timeout_time: raise IOError("Receive timeout")
OSError: Receive timeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 143, in update
await self._connect_if_need()
File "/config/custom_components/skykettle/kettle_connection.py", line 125, in _connect_if_need
self._last_auth_ok = self._auth_ok = await self.auth()
File "/config/custom_components/skykettle/skykettle.py", line 127, in auth
r = await self.command(SkyKettle.COMMAND_AUTH, key)
File "/config/custom_components/skykettle/kettle_connection.py", line 75, in command
if monotonic() >= timeout_time: raise IOError("Receive timeout")
OSError: Receive timeout
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/skykettle/kettle_connection.py", line 143, in update
await self._connect_if_need()
File "/config/custom_components/skykettle/kettle_connection.py", line 123, in _connect_if_need
raise ex
File "/config/custom_components/skykettle/kettle_connection.py", line 119, in _connect_if_need
await self._connect()
File "/config/custom_components/skykettle/kettle_connection.py", line 93, in _connect
await self._client.connect()
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 167, in connect
assert_reply(reply)
File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort

**Comment by gu3sswho** [comment]
Аналогично, постоянно теряется соединение с чайником. Очень жаль, полезная вещь.

**Comment by ClusterM** [comment]
Думаю, после перехода Home Assistant на свой собственный API для Bluetooth, я могу переводить все стрелки на них.

**Comment by Nemiroff** [comment]
> Думаю, после перехода Home Assistant на свой собственный API для Bluetooth, я могу переводить все стрелки на них.

Тогда почему после перезагрузки интеграции (Именно интеграции а не HA в целом) всё возвращается в норму?

**Comment by Drafteed** [comment]
В новой версии HA будет много фиксов, может лучше станет + завезут [Remote adapters](https://rc.home-assistant.io/integrations/bluetooth/#remote-adapters) - можно будет использовать [ESPHome](https://esphome.io/) как прокси, чтобы разместить его поближе к чайнику.

**Comment by AndyZ2121** [comment]
> Думаю, после перехода Home Assistant на свой собственный API для Bluetooth, я могу переводить все стрелки на них.
Согласен. После долгих мучений с 3 интеграциями bt и ble ни одно устройство больше нескольких часов не работало, даже обычный bt сканер отваливался... Только отключив встроенную bt интеграцию bt сканер у меня работает без проблем уже 4 суток! Ble сканер у меня стабильно работает на esp32+esphome. Если не исправят в собственной bt интеграции, то думаю, про сканирование встроенного bt можно забыть...

**Comment by AndyZ2121** [comment]
> Думаю, после перехода Home Assistant на свой собственный API для Bluetooth, я могу переводить все стрелки на них.
Согласен. После долгих мучений с 3 интеграциями bt и ble ни одно устройство больше нескольких часов не работало, даже обычный bt сканер отваливался... Только отключив встроенную bt интеграцию bt сканер у меня работает без проблем уже 4 суток! Ble сканер у меня стабильно работает на esp32+esphome. Если не исправят в собственной bt интеграции, то думаю, про сканирование встроенного bt можно забыть...

**Comment by AndyZ2121** [comment]
> Думаю, после перехода Home Assistant на свой собственный API для Bluetooth, я могу переводить все стрелки на них.

Согласен. После долгих мучений с 3 интеграциями bt и ble ни одно устройство больше нескольких часов не работало, даже обычный bt сканер отваливался... Только отключив встроенную bt интеграцию bt сканер у меня работает без проблем уже 4 суток! Ble сканер у меня стабильно работает на esp32+esphome. Если не исправят в собственной bt интеграции, то думаю, про сканирование встроенного bt можно забыть..

**Comment by siriuske** [comment]
Обновился на последнюю версию ХА 2022.9.2
Интеграцию переустановил, симптомы те же, через пару дней идеальной работы полностью теряется коннект, если рестартануть ХА в логах такое
`2022-09-13 17:43:44.266 DEBUG (MainThread) [custom_components.skykettle.kettle_connection] Traceback (most recent call last):
  File "/config/custom_components/skykettle/kettle_connection.py", line 143, in update
    await self._connect_if_need()
  File "/config/custom_components/skykettle/kettle_connection.py", line 123, in _connect_if_need
    raise ex
  File "/config/custom_components/skykettle/kettle_connection.py", line 119, in _connect_if_need
    await self._connect()
  File "/config/custom_components/skykettle/kettle_connection.py", line 93, in _connect
    await self._client.connect()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 167, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] le-connection-abort-by-local

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/skykettle/kettle_connection.py", line 143, in update
    await self._connect_if_need()
  File "/config/custom_components/skykettle/kettle_connection.py", line 123, in _connect_if_need
    raise ex
  File "/config/custom_components/skykettle/kettle_connection.py", line 119, in _connect_if_need
    await self._connect()
  File "/config/custom_components/skykettle/kettle_connection.py", line 93, in _connect
    await self._client.connect()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 167, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] le-connection-abort-by-local

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/skykettle/kettle_connection.py", line 143, in update
    await self._connect_if_need()
  File "/config/custom_components/skykettle/kettle_connection.py", line 123, in _connect_if_need
    raise ex
  File "/config/custom_components/skykettle/kettle_connection.py", line 119, in _connect_if_need
    await self._connect()
  File "/config/custom_components/skykettle/kettle_connection.py", line 93, in _connect
    await self._client.connect()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 167, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] le-connection-abort-by-local`

**Comment by ClusterM** [comment]
Это на релизе или версии из мастера?

**Comment by siriuske** [comment]
версия интеграции релиз 2.0

**Comment by ClusterM** [comment]
> версия интеграции релиз 2.0

Попробуйте потестировать версию из мастера.

**Comment by siriuske** [comment]
удалил интеграцию из ХА, потом и хакс, ребутнулся, установил из мастера, ребутнулся и сходу получаю эту же ошибку, не могу даже первый коннект настроить

**Comment by Nemiroff** [comment]
На последних версиях потеря конекта с чайником вроде вылечилась. Теперь нет необходимости перезагружать

**Comment by siriuske** [comment]
у меня увы нет, сбросил настройки чайника и интеграцию удалил, установил все снова, 2 недели работает без разрывов а потом разрывы как по рубильнику включаются
![image](https://user-images.githubusercontent.com/61635979/203501445-8d4c6efb-a71f-4cbf-9027-770ca3ed9a78.png)

**Comment by TonTon-Macout** [comment]
никто не пробовал внешний юсб блютус воткнуть? заведется? 
а то на рспбери таже фигня, все блютус устройства отваливаются периодически
есть еще варик внешнюю антену припаять

**Comment by AndyZ2121** [comment]
> никто не пробовал внешний юсб блютус воткнуть? заведется? а то на рспбери таже фигня, все блютус устройства отваливаются периодически есть еще варик внешнюю антену припаять

У меня на неттопе ВТ отваливается сам по себе, установил отдельно для чайника RPi3+, работает стабильно, но только одна эта интеграция. При добавлении другой BT интеграции - увеличивается нагрузка на проц сразу до 20-30% и всё перестаёт работать. Так и живем: на неттопе ХА и всё, кроме BT и отдельно малина для чайника... Круто, конечно, для чайника...

**Comment by TonTon-Macout** [comment]
> > никто не пробовал внешний юсб блютус воткнуть? заведется? а то на рспбери таже фигня, все блютус устройства отваливаются периодически есть еще варик внешнюю антену припаять
> 
> У меня на неттопе ВТ отваливается сам по себе, установил отдельно для чайника RPi3+, работает стабильно, но только одна эта интеграция. При добавлении другой BT интеграции - увеличивается нагрузка на проц сразу до 20-30% и всё перестаёт работать. Так и живем: на неттопе ХА и всё, кроме BT и отдельно малина для чайника... Круто, конечно, для чайника...

чето не звучит как решение и так для замка отдельный сяомивский хаб висит. зоопарк нехочется разводить.
нашел у себя блютус донгл, воткнул, штатной интеграцией опознался установился но ни чайник ни бле термометр ни чего не запустилось. В принципе на офф сайте есть список совместимых и один из них на ли за 1500 продается, вот думаю попробовать
