### ISSUE TITLE
Неизвестная ошибка, смотрите логи.

### ISSUE THREAD

**Issue by fixbad** [ClusterM/skykettle-ha#3]
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.skykettle.config_flow
Source: custom_components/skykettle/config_flow.py:94
Integration: SkyKettle (documentation, issues)
First occurred: 17:53:12 (2 occurrences)
Last logged: 17:59:24

Traceback (most recent call last): File "/config/custom_components/skykettle/config_flow.py", line 73, in async_step_scan macs = await ble_scan(scan_time=BLE_SCAN_TIME) File "/config/custom_components/skykettle/ble_scan.py", line 34, in ble_scan raise Exception(err) Exception: Enable scan failed: I/O error

**Comment by ClusterM** [comment]
Try to type:
```
hcitool lescan
```
in console (under the same user as Home Assistant), what will it print?

**Comment by fixbad** [comment]
> Try to type:
> 
> ```
> hcitool lescan
> ```
> 
> in console (under the same user as Home Assistant), what will it print?

hcitool lescan
bash: hcitool: command not found

**Comment by fixbad** [comment]
[core-ssh ~]$ bluetoothctl
Agent registered
[CHG] Controller F0:A3:B2:AC:44:08 Pairable: yes

**Comment by ClusterM** [comment]
You need to install `hcitool`.
https://command-not-found.com/hcitool

**Comment by ClusterM** [comment]
Did it help?
